on:
  push:
    branches:
      - "main"
env:
  BACKEND_WORK_DIR: ${{ github.workspace }}/server
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: devsareno
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ${{ env.BACKEND_WORK_DIR }}
          push: true
          tags: devsareno/webcuss:${{ github.sha }},devsareno/webcuss:latest
