on:
  push:
    branches:
      - "main"
env:
  BACKEND_WORK_DIR: ${{ github.workspace }}/server
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8  # tag=v3.1.0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@e81a89b1732b9c48d79cd809d8d81d79c4647a18  # tag=v2.1.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8c0edbc76e98fa90f69d9a2c020dcb50019dc325  # tag=v2.2.1
      - name: Login to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a  # tag=v2.1.0
        with:
          username: devsareno
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@c56af957549030174b10d6867f20e78cfd7debc5  # tag=v3.2.0
        with:
          context: ${{ env.BACKEND_WORK_DIR }}
          push: true
          tags: devsareno/webcuss:${{ github.sha }},devsareno/webcuss:latest
